#!/usr/bin/env python3
"""Genere src/gui/T4CInvItemIconMap.gen.cpp depuis VisualObjectList.cpp (BIND_INV)."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VOL = ROOT / "CLIENT168_RC14h_OK/1.68RC14h/Client/T4C Client/VisualObjectList.cpp"
APP = ROOT / "CLIENT168_RC14h_OK/1.68RC14h/Client/T4C Client/Apparence.h"
OUT = ROOT / "src/gui/T4CInvItemIconMap.gen.cpp"


def main() -> None:
    vol = VOL.read_text(encoding="latin-1")
    app = APP.read_text(encoding="latin-1")

    consts: dict[str, int] = {}
    for m in re.finditer(r"const unsigned int (__OBJGROUP_\w+)\s*=\s*(\d+)", app):
        consts[m.group(1)] = int(m.group(2))

    entries: dict[int, str] = {}
    for m in re.finditer(r"^\s*BIND_INV\s*\(\s*(\d+)\s*,\s*\"([^\"]+)\"\s*\)", vol, re.M):
        entries[int(m.group(1))] = m.group(2)
    for m in re.finditer(r"^\s*BIND_INV\s*\(\s*(__OBJGROUP_\w+)\s*,\s*\"([^\"]+)\"\s*\)", vol, re.M):
        k = consts.get(m.group(1))
        if k is not None:
            entries[k] = m.group(2)

    lines = [
        "// Auto-generated by scripts/generate_t4c_inv_icon_map.py — do not edit.",
        "#if defined(LINUX_PORT)",
        "",
        "#include <cstdint>",
        "#include <unordered_map>",
        "",
        "const std::unordered_map<std::uint16_t, const char *> &T4CInvItemIconMap() {",
        "    static const std::unordered_map<std::uint16_t, const char *> kMap = {",
    ]
    for k in sorted(entries):
        name = entries[k].replace("\\", "\\\\")
        lines.append(f'        {{{k}, "{name}"}},')
    lines += [
        "    };",
        "    return kMap;",
        "}",
        "",
        "#endif",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT} ({len(entries)} entries, max id {max(entries)})")


if __name__ == "__main__":
    main()
